/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Fatih
 */
public class OdemeEkrani extends javax.swing.JFrame {
    static String eposta;
    static int alisverisId;
    /**
     * Creates new form OdemeEkrani
     */
    public OdemeEkrani(String email,int id) {
        initComponents();
        eposta=email;
        alisverisId=id;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        musteriAdiText = new javax.swing.JTextField();
        kartNoText = new javax.swing.JTextField();
        sonKullanimText = new javax.swing.JTextField();
        ccvText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kart Sahibinin Adı : ");

        jLabel2.setText("Kart Numarası : ");

        jLabel3.setText("Son Kullanım Tarihi :");

        jLabel4.setText("CCV kodu : ");

        jButton1.setText("ONAYLA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addGap(239, 239, 239))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(kartNoText)
                                        .addComponent(sonKullanimText, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                        .addComponent(musteriAdiText)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ccvText, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musteriAdiText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kartNoText)
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sonKullanimText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccvText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String kartSahibiAdi = musteriAdiText.getText();
       String kartNo = kartNoText.getText();
       String sonKullanım = sonKullanimText.getText();
       String ccvKodu = ccvText.getText();
        try {
            /**
             * *** Bağlantı kurulumu ****
             */
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/VYProje",
                    "postgres", "147852");
            if (conn != null) {
                System.out.println("Veritabanına bağlandı!");
            } else {
                System.out.println("Bağlantı girişimi başarısız!");
            }

            String sql = "INSERT INTO odeme(kartsahibi,kartnumarasi,sonkullanim,kartguvenlikkodu,siparisid) VALUES(?,?,?,?,?)";

            /**
             * *** Sorgu çalıştırma ****
             */
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, kartSahibiAdi);
            stmt.setString(2,kartNo);
            stmt.setString(3, sonKullanım);
            stmt.setShort(4, Short.valueOf(ccvKodu));
            stmt.setInt(5,alisverisId);
            stmt.execute();

            /**
             * *** Bağlantı sonlandırma ****
             */
            conn.close();

       
            
           
            /**
             * *** Kaynakları serbest bırak ****
             */
            stmt.close();
            JOptionPane.showMessageDialog(this, "Siparişiniz alınmıştır,teşekkür ederiz...");
             AlisverisEkrani alisverisEkrani = new AlisverisEkrani(eposta);
            this.setVisible(false);
            alisverisEkrani.setVisible(true);
            
            
           
            

        } catch (Exception e) {
            e.printStackTrace();
        }
         try {
                Connection conn2 = DriverManager.getConnection("jdbc:postgresql://localhost:5432/VYProje",
                    "postgres", "147852");
                if (conn2 != null) {
                    System.out.println("Veritabanına bağlandı!");
                } else {
                 System.out.println("Bağlantı girişimi başarısız!");
                }
                
                String sqlString="UPDATE sepet SET email='NULL' WHERE email=?";
                PreparedStatement stmt2 = conn2.prepareStatement(sqlString);
                stmt2.setString(1, eposta);
                stmt2.execute();
                conn2.close();
                stmt2.close();
                
            } catch (Exception e) {
                e.printStackTrace();
            }
          try {
                Connection conn2 = DriverManager.getConnection("jdbc:postgresql://localhost:5432/VYProje",
                    "postgres", "147852");
                if (conn2 != null) {
                    System.out.println("Veritabanına bağlandı!");
                } else {
                 System.out.println("Bağlantı girişimi başarısız!");
                }
                
                String sqlString="UPDATE siparis SET musterieposta='(alindi)"+eposta+"' WHERE musterieposta=?";
                PreparedStatement stmt2 = conn2.prepareStatement(sqlString);
                stmt2.setString(1, eposta);
                stmt2.execute();
                conn2.close();
                stmt2.close();
                
            } catch (Exception e) {
                e.printStackTrace();
            }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OdemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OdemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OdemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OdemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OdemeEkrani(eposta,alisverisId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ccvText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField kartNoText;
    private javax.swing.JTextField musteriAdiText;
    private javax.swing.JTextField sonKullanimText;
    // End of variables declaration//GEN-END:variables
}
